import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import MainframeBg from "@/components/MainframeBg/MainframeBg";
import Header from "@/components/Header/Header";
import "./globals.css";
import localFont from "next/font/local";

const bulgaria = localFont({
   src: "../../public/fonts/Bulgaria Moderna Pro/Bulgaria Moderna Pro.otf",
   variable: "--font-bulgaria",
   display: "swap",
});

const geistSans = Geist({
   variable: "--font-geist-sans",
   subsets: ["latin"],
});

const geistMono = Geist_Mono({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html
         lang="en"
         className={`${geistSans.variable} ${geistMono.variable} ${bulgaria.variable} h-full antialiased `}
      >
         <body className="min-h-full flex flex-col bg-background">
            <MainframeBg />
            {children}
         </body>
      </html>
   );
}
